[flake8]
# Error Codes: https://flake8.pycqa.org/en/latest/user/error-codes.html
ignore = E501,W503
exclude =
    __pycache__/
    .obsidian/
    venv/
    .venv/
    .vscode/
    index/
    logs/
    test/
    tests/
    migrations/
    app/static/data/
    data/
    app.db
max-line-length = 99
