"""flask user changes

Revision ID: 007a07f7c21f
Revises: 323a66d1e12a
Create Date: 2019-09-17 17:04:18.825540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007a07f7c21f'
down_revision = '323a66d1e12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_uid', table_name='users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(),
                                      server_default='0', nullable=False))
        batch_op.add_column(sa.Column('email_confirmed_at',
                                      sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(
            length=64), server_default='', nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(
            length=256), server_default='', nullable=False))
        batch_op.drop_column('uid')
        batch_op.drop_column('username')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('is_whitelisted')
        batch_op.drop_column('is_pi')
        batch_op.drop_column('is_account_expired')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email_confirmed_at')
        batch_op.drop_column('active')
        batch_op.add_column(sa.Column('uid',
                                      sa.Integer()))
        batch_op.add_column(sa.Column('username',
                                      sa.VARCHAR(64)))
        batch_op.add_column(sa.Column('password_hash',
                                      sa.VARCHAR(128)))
        batch_op.add_column(sa.Column('is_whitelisted',
                                      sa.Boolean(),
                                      nullable=False))
        batch_op.add_column(sa.Column('is_pi',
                                      sa.Boolean(),
                                      nullable=False))
        batch_op.add_column(sa.Column('is_account_expired',
                                      sa.Boolean(),
                                      nullable=False))
    op.create_index('ix_users_username','users',['username'], unique=True)
    op.create_index('ix_users_uid','users',['uid'], unique=True)

    # ### end Alembic commands ###
