"""adding affiliation types

Revision ID: 05e29a68342f
Revises: ccc6a814baf2
Create Date: 2019-09-19 08:16:49.517859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e29a68342f'
down_revision = 'ccc6a814baf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50),
                              server_default='', nullable=False),
                    sa.Column('label', sa.String(length=255),
                              server_default='', nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('affiliation_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('affiliation_type_id',
                                    'affiliation_type',
                                    ['affiliation_type_id'],
                                    ['id'])
        batch_op.drop_column('affiliation_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliation_type',
                                      sa.VARCHAR(length=3), nullable=False))
        batch_op.drop_constraint('affiliation_type_id', type_='foreignkey')
        batch_op.drop_column('affiliation_type_id')

    op.drop_table('affiliation_type')
    # ### end Alembic commands ###
