"""empty message

Revision ID: 20d5116a59e9
Revises: 492f241ced60
Create Date: 2019-11-29 15:16:48.506226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d5116a59e9'
down_revision = '492f241ced60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index('ix_datasets_download_path')
        batch_op.drop_index('ix_datasets_raw_data_url')
        batch_op.drop_column('download_path')
        batch_op.drop_column('raw_data_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data_url', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('download_path', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_datasets_raw_data_url', ['raw_data_url'], unique=False)
        batch_op.create_index('ix_datasets_download_path', ['download_path'], unique=False)

    # ### end Alembic commands ###
