"""empty message

Revision ID: 2430e2e7ca9e
Revises: 56534f06236c
Create Date: 2020-05-13 13:41:18.622393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2430e2e7ca9e'
down_revision = '56534f06236c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index('ix_datasets_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index('ix_datasets_description', ['description'], unique=False)

    # ### end Alembic commands ###
