"""add matomo_daily_get_page_urls_summary table

Revision ID: 4060ec5b1973
Revises: 7dc3483b3196
Create Date: 2021-02-18 10:57:19.248795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4060ec5b1973'
down_revision = '7dc3483b3196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matomo_daily_get_page_urls_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('nb_hits', sa.Integer(), nullable=True),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('nb_uniq_visitors', sa.Integer(), nullable=True),
    sa.Column('sum_time_spent', sa.Integer(), nullable=True),
    sa.Column('avg_time_on_page', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matomo_daily_get_page_urls_summary')
    # ### end Alembic commands ###
