"""rename dataset table indexes

Revision ID: 4237758a2ed7
Revises: c938dd4a9305
Create Date: 2019-10-07 14:02:09.485809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4237758a2ed7'
down_revision = 'c938dd4a9305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_datasets_annex_uuid'), 'datasets', ['annex_uuid'], unique=True)
    op.create_index(op.f('ix_datasets_category'), 'datasets', ['category'], unique=False)
    op.create_index(op.f('ix_datasets_dataset_id'), 'datasets', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_datasets_description'), 'datasets', ['description'], unique=False)
    op.create_index(op.f('ix_datasets_download_path'), 'datasets', ['download_path'], unique=False)
    op.create_index(op.f('ix_datasets_files'), 'datasets', ['files'], unique=False)
    op.create_index(op.f('ix_datasets_format'), 'datasets', ['format'], unique=False)
    op.create_index(op.f('ix_datasets_is_private'), 'datasets', ['is_private'], unique=False)
    op.create_index(op.f('ix_datasets_modality'), 'datasets', ['modality'], unique=False)
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_index(op.f('ix_datasets_num_downloads'), 'datasets', ['num_downloads'], unique=False)
    op.create_index(op.f('ix_datasets_num_likes'), 'datasets', ['num_likes'], unique=False)
    op.create_index(op.f('ix_datasets_num_subjects'), 'datasets', ['num_subjects'], unique=False)
    op.create_index(op.f('ix_datasets_num_views'), 'datasets', ['num_views'], unique=False)
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_datasets_raw_data_url'), 'datasets', ['raw_data_url'], unique=False)
    op.create_index(op.f('ix_datasets_size'), 'datasets', ['size'], unique=False)
    op.create_index(op.f('ix_datasets_sources'), 'datasets', ['sources'], unique=False)
    op.create_index(op.f('ix_datasets_version'), 'datasets', ['version'], unique=False)
    op.drop_index('ix_newdatasets_annex_uuid', table_name='datasets')
    op.drop_index('ix_newdatasets_category', table_name='datasets')
    op.drop_index('ix_newdatasets_dataset_id', table_name='datasets')
    op.drop_index('ix_newdatasets_description', table_name='datasets')
    op.drop_index('ix_newdatasets_download_path', table_name='datasets')
    op.drop_index('ix_newdatasets_files', table_name='datasets')
    op.drop_index('ix_newdatasets_format', table_name='datasets')
    op.drop_index('ix_newdatasets_is_private', table_name='datasets')
    op.drop_index('ix_newdatasets_modality', table_name='datasets')
    op.drop_index('ix_newdatasets_name', table_name='datasets')
    op.drop_index('ix_newdatasets_num_downloads', table_name='datasets')
    op.drop_index('ix_newdatasets_num_likes', table_name='datasets')
    op.drop_index('ix_newdatasets_num_subjects', table_name='datasets')
    op.drop_index('ix_newdatasets_num_views', table_name='datasets')
    op.drop_index('ix_newdatasets_owner_id', table_name='datasets')
    op.drop_index('ix_newdatasets_raw_data_url', table_name='datasets')
    op.drop_index('ix_newdatasets_size', table_name='datasets')
    op.drop_index('ix_newdatasets_sources', table_name='datasets')
    op.drop_index('ix_newdatasets_version', table_name='datasets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_newdatasets_version', 'datasets', ['version'], unique=False)
    op.create_index('ix_newdatasets_sources', 'datasets', ['sources'], unique=False)
    op.create_index('ix_newdatasets_size', 'datasets', ['size'], unique=False)
    op.create_index('ix_newdatasets_raw_data_url', 'datasets', ['raw_data_url'], unique=False)
    op.create_index('ix_newdatasets_owner_id', 'datasets', ['owner_id'], unique=False)
    op.create_index('ix_newdatasets_num_views', 'datasets', ['num_views'], unique=False)
    op.create_index('ix_newdatasets_num_subjects', 'datasets', ['num_subjects'], unique=False)
    op.create_index('ix_newdatasets_num_likes', 'datasets', ['num_likes'], unique=False)
    op.create_index('ix_newdatasets_num_downloads', 'datasets', ['num_downloads'], unique=False)
    op.create_index('ix_newdatasets_name', 'datasets', ['name'], unique=False)
    op.create_index('ix_newdatasets_modality', 'datasets', ['modality'], unique=False)
    op.create_index('ix_newdatasets_is_private', 'datasets', ['is_private'], unique=False)
    op.create_index('ix_newdatasets_format', 'datasets', ['format'], unique=False)
    op.create_index('ix_newdatasets_files', 'datasets', ['files'], unique=False)
    op.create_index('ix_newdatasets_download_path', 'datasets', ['download_path'], unique=False)
    op.create_index('ix_newdatasets_description', 'datasets', ['description'], unique=False)
    op.create_index('ix_newdatasets_dataset_id', 'datasets', ['dataset_id'], unique=1)
    op.create_index('ix_newdatasets_category', 'datasets', ['category'], unique=False)
    op.create_index('ix_newdatasets_annex_uuid', 'datasets', ['annex_uuid'], unique=1)
    op.drop_index(op.f('ix_datasets_version'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_sources'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_size'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_raw_data_url'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_num_views'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_num_subjects'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_num_likes'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_num_downloads'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_modality'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_is_private'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_format'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_files'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_download_path'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_description'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_dataset_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_category'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_annex_uuid'), table_name='datasets')
    # ### end Alembic commands ###
