"""empty message

Revision ID: 5140aacb6857
Revises: 63e89f0e8696
Create Date: 2021-02-15 18:21:36.669168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5140aacb6857'
down_revision = '63e89f0e8696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matomo_daily_visits_summary', schema=None) as batch_op:
        batch_op.alter_column('nb_actions_per_visit',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matomo_daily_visits_summary', schema=None) as batch_op:
        batch_op.alter_column('nb_actions_per_visit',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
