"""empty message

Revision ID: 56534f06236c
Revises: a8f98d953599
Create Date: 2020-04-29 12:35:38.699688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56534f06236c'
down_revision = 'a8f98d953599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('dataset_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('dataset_id',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
