"""empty message

Revision ID: 63e89f0e8696
Revises: c7e43e06099c
Create Date: 2021-02-15 18:11:04.926744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e89f0e8696'
down_revision = 'c7e43e06099c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matomo_daily_visits_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nb_actions', sa.Integer(), nullable=True))
        batch_op.drop_column('nb_action')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matomo_daily_visits_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nb_action', sa.INTEGER(), nullable=True))
        batch_op.drop_column('nb_actions')

    # ### end Alembic commands ###
