"""empty message

Revision ID: 66532ed317c4
Revises: ab927684d5ea
Create Date: 2021-02-15 16:28:57.270119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66532ed317c4'
down_revision = 'ab927684d5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matomo_daily_visits_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('avg_time_on_site', sa.Integer(), nullable=True),
    sa.Column('bounce_cound', sa.Integer(), nullable=True),
    sa.Column('max_actions', sa.Integer(), nullable=True),
    sa.Column('nb_action', sa.Integer(), nullable=True),
    sa.Column('nb_actions_per_visit', sa.Integer(), nullable=True),
    sa.Column('nb_uniq_visitors', sa.Integer(), nullable=True),
    sa.Column('nb_users', sa.Integer(), nullable=True),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('nb_visits_converted', sa.Integer(), nullable=True),
    sa.Column('sum_visit_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matomo_daily_visits_summary')
    # ### end Alembic commands ###
