"""add matomo_daily_visits_summary table

Revision ID: 7dc3483b3196
Revises: ab927684d5ea
Create Date: 2021-02-18 10:01:46.338397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc3483b3196'
down_revision = '5abb9f01fedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matomo_daily_visits_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('avg_time_on_site', sa.Integer(), nullable=True),
    sa.Column('bounce_count', sa.Integer(), nullable=True),
    sa.Column('max_actions', sa.Integer(), nullable=True),
    sa.Column('nb_actions', sa.Integer(), nullable=True),
    sa.Column('nb_actions_per_visit', sa.Float(), nullable=True),
    sa.Column('nb_uniq_visitors', sa.Integer(), nullable=True),
    sa.Column('nb_users', sa.Integer(), nullable=True),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('nb_visits_converted', sa.Integer(), nullable=True),
    sa.Column('sum_visit_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matomo_daily_visits_summary')
    # ### end Alembic commands ###
