"""empty message

Revision ID: 7fe63dca6b42
Revises: 2430e2e7ca9e
Create Date: 2020-06-15 20:46:19.961000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe63dca6b42'
down_revision = '2430e2e7ca9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_ancestry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_dataset_id', sa.String(length=256), nullable=True),
    sa.Column('child_dataset_id', sa.String(length=256), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('dataset_ancestry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_ancestry_child_dataset_id'), ['child_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_ancestry_parent_dataset_id'), ['parent_dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_ancestry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_ancestry_parent_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_ancestry_child_dataset_id'))

    op.drop_table('dataset_ancestry')
    # ### end Alembic commands ###
