"""empty message

Revision ID: 81497cf7f0a6
Revises: b6335c811e2a
Create Date: 2019-04-22 19:28:22.366237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81497cf7f0a6'
down_revision = 'b6335c811e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('annex_uuid', sa.String(length=64), nullable=True))
    op.add_column('datasets', sa.Column('datalad_remote_annex_uuid', sa.String(length=64), nullable=True))
    op.add_column('datasets', sa.Column('download_path', sa.String(length=64), nullable=True))
    op.add_column('datasets', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_datasets_annex_uuid'), 'datasets', ['annex_uuid'], unique=True)
    op.create_index(op.f('ix_datasets_datalad_remote_annex_uuid'), 'datasets', ['datalad_remote_annex_uuid'], unique=True)
    op.create_index(op.f('ix_datasets_download_path'), 'datasets', ['download_path'], unique=False)
    op.drop_index('ix_datasets_dataset_id', table_name='datasets')
    op.create_index(op.f('ix_datasets_dataset_id'), 'datasets', ['dataset_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_dataset_id'), table_name='datasets')
    op.create_index('ix_datasets_dataset_id', 'datasets', ['dataset_id'], unique=False)
    op.drop_index(op.f('ix_datasets_download_path'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_datalad_remote_annex_uuid'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_annex_uuid'), table_name='datasets')
    op.drop_column('datasets', 'image')
    op.drop_column('datasets', 'download_path')
    op.drop_column('datasets', 'datalad_remote_annex_uuid')
    op.drop_column('datasets', 'annex_uuid')
    # ### end Alembic commands ###
