"""empty message

Revision ID: 893765cf9bde
Revises: 
Create Date: 2019-04-03 13:46:03.922012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893765cf9bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('files', sa.Integer(), nullable=True),
    sa.Column('sources', sa.Integer(), nullable=True),
    sa.Column('num_subjects', sa.Integer(), nullable=True),
    sa.Column('num_downloads', sa.Integer(), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=True),
    sa.Column('num_views', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_stats_dataset_id'), 'dataset_stats', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_dataset_stats_files'), 'dataset_stats', ['files'], unique=False)
    op.create_index(op.f('ix_dataset_stats_num_downloads'), 'dataset_stats', ['num_downloads'], unique=False)
    op.create_index(op.f('ix_dataset_stats_num_likes'), 'dataset_stats', ['num_likes'], unique=False)
    op.create_index(op.f('ix_dataset_stats_num_subjects'), 'dataset_stats', ['num_subjects'], unique=False)
    op.create_index(op.f('ix_dataset_stats_num_views'), 'dataset_stats', ['num_views'], unique=False)
    op.create_index(op.f('ix_dataset_stats_size'), 'dataset_stats', ['size'], unique=False)
    op.create_index(op.f('ix_dataset_stats_sources'), 'dataset_stats', ['sources'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('modality', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_category'), 'datasets', ['category'], unique=False)
    op.create_index(op.f('ix_datasets_dataset_id'), 'datasets', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_datasets_format'), 'datasets', ['format'], unique=False)
    op.create_index(op.f('ix_datasets_is_private'), 'datasets', ['is_private'], unique=False)
    op.create_index(op.f('ix_datasets_modality'), 'datasets', ['modality'], unique=False)
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_datasets_version'), 'datasets', ['version'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_is_private'), 'pipelines', ['is_private'], unique=False)
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=False)
    op.create_index(op.f('ix_pipelines_owner_id'), 'pipelines', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pipelines_pipeline_id'), 'pipelines', ['pipeline_id'], unique=True)
    op.create_index(op.f('ix_pipelines_version'), 'pipelines', ['version'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('oauth_id', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=False),
    sa.Column('is_pi', sa.Boolean(), nullable=False),
    sa.Column('is_account_expired', sa.Boolean(), nullable=False),
    sa.Column('affiliation', sa.String(length=128), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliation'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pipelines_version'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_pipeline_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_owner_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_is_private'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_datasets_version'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_modality'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_is_private'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_format'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_dataset_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_category'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_dataset_stats_sources'), table_name='dataset_stats')
    op.drop_index(op.f('ix_dataset_stats_size'), table_name='dataset_stats')
    op.drop_index(op.f('ix_dataset_stats_num_views'), table_name='dataset_stats')
    op.drop_index(op.f('ix_dataset_stats_num_subjects'), table_name='dataset_stats')
    op.drop_index(op.f('ix_dataset_stats_num_likes'), table_name='dataset_stats')
    op.drop_index(op.f('ix_dataset_stats_num_downloads'), table_name='dataset_stats')
    op.drop_index(op.f('ix_dataset_stats_files'), table_name='dataset_stats')
    op.drop_index(op.f('ix_dataset_stats_dataset_id'), table_name='dataset_stats')
    op.drop_table('dataset_stats')
    # ### end Alembic commands ###
