"""empty message

Revision ID: 8b136c230f4c
Revises: 81497cf7f0a6
Create Date: 2019-04-27 16:42:42.161545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b136c230f4c'
down_revision = '81497cf7f0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('datasets', sa.Column('raw_data_url', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_datasets_description'), 'datasets', ['description'], unique=False)
    op.create_index(op.f('ix_datasets_raw_data_url'), 'datasets', ['raw_data_url'], unique=False)
    op.drop_index('ix_datasets_datalad_remote_annex_uuid', table_name='datasets')
    op.drop_column('datasets', 'datalad_remote_annex_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('datalad_remote_annex_uuid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_datasets_datalad_remote_annex_uuid', 'datasets', ['datalad_remote_annex_uuid'], unique=True)
    op.drop_index(op.f('ix_datasets_raw_data_url'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_description'), table_name='datasets')
    op.drop_column('datasets', 'raw_data_url')
    op.drop_column('datasets', 'description')
    # ### end Alembic commands ###
