"""create temporary newdatasets table

Revision ID: a097b34894c1
Revises: 063cdaf656b3
Create Date: 2019-10-07 13:05:32.113803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm


# revision identifiers, used by Alembic.
revision = 'a097b34894c1'
down_revision = '063cdaf656b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newdatasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('annex_uuid', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('download_path', sa.String(length=64), nullable=True),
    sa.Column('raw_data_url', sa.String(length=128), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('modality', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=6), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('files', sa.Integer(), nullable=True),
    sa.Column('sources', sa.Integer(), nullable=True),
    sa.Column('num_subjects', sa.Integer(), nullable=True),
    sa.Column('num_downloads', sa.Integer(), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=True),
    sa.Column('num_views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newdatasets_annex_uuid'), 'newdatasets', ['annex_uuid'], unique=True)
    op.create_index(op.f('ix_newdatasets_category'), 'newdatasets', ['category'], unique=False)
    op.create_index(op.f('ix_newdatasets_dataset_id'), 'newdatasets', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_newdatasets_description'), 'newdatasets', ['description'], unique=False)
    op.create_index(op.f('ix_newdatasets_download_path'), 'newdatasets', ['download_path'], unique=False)
    op.create_index(op.f('ix_newdatasets_files'), 'newdatasets', ['files'], unique=False)
    op.create_index(op.f('ix_newdatasets_format'), 'newdatasets', ['format'], unique=False)
    op.create_index(op.f('ix_newdatasets_is_private'), 'newdatasets', ['is_private'], unique=False)
    op.create_index(op.f('ix_newdatasets_modality'), 'newdatasets', ['modality'], unique=False)
    op.create_index(op.f('ix_newdatasets_name'), 'newdatasets', ['name'], unique=False)
    op.create_index(op.f('ix_newdatasets_num_downloads'), 'newdatasets', ['num_downloads'], unique=False)
    op.create_index(op.f('ix_newdatasets_num_likes'), 'newdatasets', ['num_likes'], unique=False)
    op.create_index(op.f('ix_newdatasets_num_subjects'), 'newdatasets', ['num_subjects'], unique=False)
    op.create_index(op.f('ix_newdatasets_num_views'), 'newdatasets', ['num_views'], unique=False)
    op.create_index(op.f('ix_newdatasets_owner_id'), 'newdatasets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_newdatasets_raw_data_url'), 'newdatasets', ['raw_data_url'], unique=False)
    op.create_index(op.f('ix_newdatasets_size'), 'newdatasets', ['size'], unique=False)
    op.create_index(op.f('ix_newdatasets_sources'), 'newdatasets', ['sources'], unique=False)
    op.create_index(op.f('ix_newdatasets_version'), 'newdatasets', ['version'], unique=False)
    # ### end Alembic commands ###

    # Update table
    op.execute('INSERT INTO newdatasets SELECT d.*, ds.size, ds.files, ds.sources, ds.num_subjects, ds.num_downloads, ds.num_likes, ds.num_views FROM datasets d LEFT JOIN dataset_stats ds ON (d.dataset_id = ds.dataset_id)')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newdatasets_version'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_sources'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_size'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_raw_data_url'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_owner_id'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_num_views'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_num_subjects'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_num_likes'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_num_downloads'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_name'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_modality'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_is_private'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_format'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_files'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_download_path'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_description'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_dataset_id'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_category'), table_name='newdatasets')
    op.drop_index(op.f('ix_newdatasets_annex_uuid'), table_name='newdatasets')
    op.drop_table('newdatasets')
    # ### end Alembic commands ###
