"""empty message

Revision ID: ab927684d5ea
Revises: d3c8a8c0a684
Create Date: 2020-06-15 21:45:20.910834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab927684d5ea'
down_revision = 'd3c8a8c0a684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_ancestry', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_1', ['parent_dataset_id', 'child_dataset_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_ancestry', schema=None) as batch_op:
        batch_op.drop_constraint('uix_1', type_='unique')

    # ### end Alembic commands ###
