"""empty message

Revision ID: b6335c811e2a
Revises: 893765cf9bde
Create Date: 2019-04-16 16:01:03.694634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6335c811e2a'
down_revision = '893765cf9bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_affiliation_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_affiliation_key', 'users', ['affiliation'])
    # ### end Alembic commands ###
