"""going_to_full_name

Revision ID: c4780889e90b
Revises: 05e29a68342f
Create Date: 2019-09-19 17:58:13.325668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4780889e90b'
down_revision = '05e29a68342f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=64), server_default='', nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=64), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=64), server_default=sa.text("''"), nullable=False))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
