"""empty message

Revision ID: c7e43e06099c
Revises: 5be6e593d12d
Create Date: 2021-02-15 18:09:02.827659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e43e06099c'
down_revision = '5be6e593d12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matomo_daily_visits_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bounce_count', sa.Integer(), nullable=True))
        batch_op.drop_column('bounce_cound')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matomo_daily_visits_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bounce_cound', sa.INTEGER(), nullable=True))
        batch_op.drop_column('bounce_count')

    # ### end Alembic commands ###
