"""Add ark_id database table

Revision ID: c9de5c5c31e2
Revises: 3d982110f18c
Create Date: 2022-02-24 14:33:50.897397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9de5c5c31e2'
down_revision = '3d982110f18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ark_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ark_id', sa.String(length=128), nullable=True),
    sa.Column('intended_for', sa.String(length=12), nullable=True),
    sa.Column('dataset_id', sa.String(length=256), nullable=True),
    sa.Column('pipeline_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ark_id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    op.drop_table('ark_id')
    # ### end Alembic commands ###
