"""Add ark_id database table

Revision ID: c9de5c5c31e2
Revises: 3d982110f18c
Create Date: 2022-02-24 14:33:50.897397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9de5c5c31e2'
down_revision = '3d982110f18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ark_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ark_id', sa.String(length=128), nullable=True),
    sa.Column('dataset_id', sa.String(length=256), nullable=True),
    sa.Column('pipeline_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ark_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ark_id')
    # ### end Alembic commands ###
