"""added_last_name_and_affiliation_type

Revision ID: ccc6a814baf2
Revises: 007a07f7c21f
Create Date: 2019-09-18 08:31:29.592549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc6a814baf2'
down_revision = '007a07f7c21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliation_type', sa.Enum('pi', 'ra', 'pd', 'phd', 'ms', 'ifs', 'oth', name='affiliationtypesenum'), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('affiliation_type')

    # ### end Alembic commands ###
